<a href="https://colab.research.google.com/github/tramnal/Collab_torch/blob/main/torch_tensor_from_numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [6]:
import numpy as np

In [8]:
x = np.array([[1, 2, 3, 4],
              [4, 3, 2, 1]])
x

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [9]:
x = torch.from_numpy(x)
x

tensor([[1, 2, 3, 4],
        [4, 3, 2, 1]])

In [10]:
x = x.numpy()
x

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])